name: CI/CD Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test-and-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Poetry
              run: pipx install poetry

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: "poetry"

            - name: Install dependencies
              run: poetry install --no-root

            - name: Install Snyk CLI
              run: |
                  curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
                  chmod +x ./snyk

            # This will fail gracefully if Snyk is being buggy, but still log the error
            - name: Snyk Open Source Scan
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              run: ./snyk test --file=poetry.lock --package-manager=poetry
                  --severity-threshold=high || echo "Snyk CLI failed to connect.
                  Check Snyk.io Dashboard/Quotas."

            - name: Run Tests
              run: poetry run python -m pytest

    build-and-push:
        needs: test-and-scan
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push
              run: |
                  REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
                  docker build -t ghcr.io/$REPO_LOWER:latest .
                  docker push ghcr.io/$REPO_LOWER:latest

    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Render Deploy
              run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
